# -*- coding: utf-8 -*-
"""
/***************************************************************************
 mapasBase
                                 A QGIS plugin
 Este plugin permite visualizar/descargar mapas base del IGN
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-23
        copyright            : (C) 2023 by IGN
        email                : ign@ign.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load mapasBase class from file mapasBase.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .mapas_base import mapasBase
    return mapasBase(iface)
